{
    "data": [
        {
            "test_name": "python.EngineeringDiffraction.test_plot_presenter.test_plot_presenter",
            "latest_failed_build": "875",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "881",
                    "880",
                    "879",
                    "878",
                    "877",
                    "876",
                    "875",
                    "874",
                    "873",
                    "872",
                    "871",
                    "870",
                    "869",
                    "868",
                    "867",
                    "866",
                    "865",
                    "864",
                    "863",
                    "862",
                    "861",
                    "860",
                    "859",
                    "858",
                    "857",
                    "856",
                    "855",
                    "854",
                    "853",
                    "852"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.EngineeringDiffraction.test_plot_presenter.test_plot_presenter",
                "build": "875",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "10.76",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221209.1419\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n....EEEE.........\n======================================================================\nERROR: test_do_all_fit_sets_progress_bar_to_in_progress_then_final (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 138, in test_do_all_fit_sets_progress_bar_to_in_progress_then_final\n    self.fit_all_helper(mock_fit, do_sequential=False)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 104, in fit_all_helper\n    self.presenter.do_fit_all(ws_list, do_sequential=do_sequential)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n======================================================================\nERROR: test_do_sequential_fit (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 64, in test_do_sequential_fit\n    self.fit_all_helper(mock_fit, do_sequential=True)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 104, in fit_all_helper\n    self.presenter.do_fit_all(ws_list, do_sequential=do_sequential)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n======================================================================\nERROR: test_do_sequential_fit_does_not_use_failed_fit_as_input (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 81, in test_do_sequential_fit_does_not_use_failed_fit_as_input\n    self.presenter.do_fit_all(ws_list, do_sequential=True)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n======================================================================\nERROR: test_do_serial_fit (test_plot_presenter.FittingPlotPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 1325, in patched\n    return func(*newargs, **newkeywargs)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 68, in test_do_serial_fit\n    self.fit_all_helper(mock_fit, do_sequential=False)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/plotting/test/test_plot_presenter.py&quot;, line 104, in fit_all_helper\n    self.presenter.do_fit_all(ws_list, do_sequential=do_sequential)\nTypeError: do_fit_all() missing 1 required positional argument: &#x27;ws_name_list&#x27;\n\n----------------------------------------------------------------------\nRan 17 tests in 1.800s\n\nFAILED (errors=4)\n\n          Start 1871: MDAlgorithmsTest_IntegrateEllipsoidsTwoStepTest\n"
            }
        },
        {
            "test_name": "python.MuonQt5.basic_fitting_view_test.basic_fitting_view_test",
            "latest_failed_build": "852",
            "agent_name": "Mac",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "881",
                    "880",
                    "879",
                    "878",
                    "877",
                    "876",
                    "875",
                    "874",
                    "873",
                    "872",
                    "871",
                    "870",
                    "869",
                    "868",
                    "867",
                    "866",
                    "865",
                    "864",
                    "863",
                    "862",
                    "861",
                    "860",
                    "859",
                    "858",
                    "857",
                    "856",
                    "855",
                    "854",
                    "853",
                    "852"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.MuonQt5.basic_fitting_view_test.basic_fitting_view_test",
                "build": "852",
                "agent_name": "Mac",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "8.69",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221206.2054\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nEEEEEEEEEEEEEEEEEEEEEEEEEE\n======================================================================\nERROR: test_that_enable_view_does_enable_the_tab_if_there_are_datasets_loaded (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_enable_view_does_not_enable_the_tab_if_there_are_no_datasets_loaded (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_hide_evaluate_function_as_checkbox_will_hide_the_evaluate_function_table_row (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_hide_exclude_range_checkbox_will_hide_the_exclude_range_table_row (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_it_is_possible_to_set_the_end_x_to_a_different_value (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_it_is_possible_to_set_the_start_x_to_a_different_value (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_set_current_dataset_index_will_set_the_current_dataset_index_in_the_function_browser (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_set_datasets_in_function_browser_will_set_the_datasets_in_the_function_browser (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_show_plot_guess_end_x_will_show_plot_guess_end_x_row (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_show_plot_guess_points_will_show_plot_guess_points_row (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_show_plot_guess_start_x_will_show_plot_guess_start_x_row (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_fit_to_raw_checkbox_value_can_be_changed_as_expected (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_function_name_can_be_changed_as_expected (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_plot_guess_checkbox_can_be_ticked_as_expected (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_undo_fit_button_can_be_enabled_as_expected_when_the_number_of_undos_is_above_zero (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_has_been_initialized_with_the_exclude_range_start_and_end_x_options_not_visible (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_has_been_initialized_with_the_raw_data_option_hidden_when_it_is_a_frequency_domain (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_has_been_initialized_with_the_raw_data_option_shown_when_it_is_not_a_frequency_domain (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_fit_status_labels_will_display_fit_successful_if_all_fits_are_successful (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_fit_status_labels_will_display_fits_failed_if_some_of_the_fits_fail (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_fit_status_labels_will_display_no_fit_if_the_success_list_is_empty (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_function_browser_parameters_will_clear_the_function_if_the_function_provided_is_none (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_function_browser_parameters_will_update_the_parameters_of_the_function_for_single_fit (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_global_fit_status_label_will_display_fit_successful_if_all_fits_are_successful (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_global_fit_status_label_will_display_fits_failed_if_some_of_the_fits_fail (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_global_fit_status_label_will_display_no_fit_if_the_success_list_is_empty (basic_fitting_view_test.BasicFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;BasicFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/basic_fitting/basic_fitting_view_test.py&quot;, line 32, in setUp\n    self.view = BasicFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n----------------------------------------------------------------------\nRan 26 tests in 0.747s\n\nFAILED (errors=26)\n\n          Start 2179: python.MuonQt5.basic_fitting_view_test.basic_fitting_view_test\n"
            }
        }
    ]
}