{
    "data": [
        {
            "test_name": "python.MuonQt5.general_fitting_view_test.general_fitting_view_test",
            "latest_failed_build": "620",
            "agent_name": "Mac",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "628",
                    "627",
                    "626",
                    "625",
                    "624",
                    "623",
                    "622",
                    "621",
                    "620",
                    "619",
                    "618",
                    "617",
                    "616",
                    "615",
                    "614",
                    "613",
                    "612",
                    "611",
                    "610",
                    "609",
                    "608",
                    "607",
                    "606",
                    "605",
                    "604",
                    "603",
                    "602",
                    "601",
                    "600",
                    "599"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.MuonQt5.general_fitting_view_test.general_fitting_view_test",
                "build": "620",
                "agent_name": "Mac",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "8.91",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221115.1527\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nEEEEEEEEEEEE\n======================================================================\nERROR: test_that_current_dataset_index_will_return_none_when_there_is_nothing_selected_in_the_combobox (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_current_dataset_index_will_return_the_expected_dataset_index (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_number_of_datasets_will_return_the_expected_number_of_datasets (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_setup_fit_by_specifier_will_add_fit_specifiers_to_the_relevant_checkbox (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_switch_to_simultaneous_will_change_the_relevant_label (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_switch_to_single_will_change_the_relevant_label (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_current_dataset_name_can_be_set_as_expected (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_current_dataset_name_will_not_change_the_selected_dataset_if_the_provided_dataset_does_not_exist (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_simultaneous_fit_by_can_be_set_as_expected (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_the_view_can_be_initialized_without_an_error (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_dataset_name_combo_box_will_select_the_previously_selected_item_if_it_still_exists (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n======================================================================\nERROR: test_that_update_dataset_name_combo_box_will_set_the_names_in_the_dataset_name_combobox (general_fitting_view_test.GeneralFittingViewTest)\n----------------------------------------------------------------------\nAttributeError: &#x27;GeneralFittingView&#x27; object has no attribute &#x27;y&#x27;\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/test/Muon/fitting_widgets/general_fitting/general_fitting_view_test.py&quot;, line 20, in setUp\n    self.view = GeneralFittingView()\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/general_fitting/general_fitting_view.py&quot;, line 25, in __init__\n    super(GeneralFittingView, self).__init__(parent)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Muon/GUI/Common/fitting_widgets/basic_fitting/basic_fitting_view.py&quot;, line 29, in __init__\n    self.setupUi(self)\n  File &quot;&lt;string&gt;&quot;, line 31, in setupUi\nSystemError: &lt;built-in function connectSlotsByName&gt; returned a result with an error set\n\n----------------------------------------------------------------------\nRan 12 tests in 0.660s\n\nFAILED (errors=12)\n\n          Start 2183: python.MuonQt5.general_fitting_view_test.general_fitting_view_test\n"
            }
        },
        {
            "test_name": "CrystalTest_PeakIntensityVsRadiusTest",
            "latest_failed_build": "606",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "628",
                    "627",
                    "626",
                    "625",
                    "624",
                    "623",
                    "622",
                    "621",
                    "620",
                    "619",
                    "618",
                    "617",
                    "616",
                    "615",
                    "614",
                    "613",
                    "612",
                    "611",
                    "610",
                    "609",
                    "608",
                    "607",
                    "606",
                    "605",
                    "604",
                    "603",
                    "602",
                    "601",
                    "600",
                    "599"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "CrystalTest_PeakIntensityVsRadiusTest",
                "build": "606",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.44",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.1209\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nDllOpen-[Error] Could not open library /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib: dlopen(/Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib, 10): Symbol not found: _PyBaseObject_Type\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\nRunning 7 testsCreateMDWorkspace-[Notice] CreateMDWorkspace started\nCreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.00 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.00 seconds\n.CreateMDWorkspace-[Notice] CreateMDWorkspace started\nCreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.00 seconds\nFakeMDEventData-[Notice] FakeMDEventData started\nFakeMDEventData-[Notice] FakeMDEventData successful, Duration 0.00 seconds\nPeakIntensityVsRadius-[Notice] PeakIntensityVsRadius started\nSegmentation fault\n\n          Start  153: ParallelTest_ThreadingBackendTest\n"
            }
        },
        {
            "test_name": "MDAlgorithmsTest_IntegratePeaksMD2Test",
            "latest_failed_build": "606",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "628",
                    "627",
                    "626",
                    "625",
                    "624",
                    "623",
                    "622",
                    "621",
                    "620",
                    "619",
                    "618",
                    "617",
                    "616",
                    "615",
                    "614",
                    "613",
                    "612",
                    "611",
                    "610",
                    "609",
                    "608",
                    "607",
                    "606",
                    "605",
                    "604",
                    "603",
                    "602",
                    "601",
                    "600",
                    "599"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "MDAlgorithmsTest_IntegratePeaksMD2Test",
                "build": "606",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "0.50",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.1209\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nDllOpen-[Error] Could not open library /Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib: dlopen(/Users/builder/Jenkins/workspace/pull_requests-conda-osx/build/bin/libMantidPythonInterfaceCore.dylib, 10): Symbol not found: _PyBaseObject_Type\n  Referenced from: /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\n  Expected in: flat namespace\n in /Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/libboost_python38.dylib\nRunning 30 tests.CreateMDWorkspace-[Notice] CreateMDWorkspace started\nCreateMDWorkspace-[Notice] CreateMDWorkspace successful, Duration 0.00 seconds\nLogger_simpleRun-[Notice] Running simpleRun with inputs: shouldPass:1 numberValuesPeakRadius:1 numberValuesBkgInnerRadius:1 numberValuesBkgOuterRadius:1 cyl:0 ellip:0\nIntegratePeaksMD-[Notice] IntegratePeaksMD started\nIntegratePeaksMD-[Error] Can&#x27;t execute MaskBTP algorithm for this instrument to set edge for IntegrateIfOnEdge option\nSegmentation fault\n\n          Start 1607: python.algorithms.SaveP2DTest.SaveP2DTest\n"
            }
        },
        {
            "test_name": "python.algorithms.HB3AIntegratePeaksTest.HB3AIntegratePeaksTest",
            "latest_failed_build": "606",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "628",
                    "627",
                    "626",
                    "625",
                    "624",
                    "623",
                    "622",
                    "621",
                    "620",
                    "619",
                    "618",
                    "617",
                    "616",
                    "615",
                    "614",
                    "613",
                    "612",
                    "611",
                    "610",
                    "609",
                    "608",
                    "607",
                    "606",
                    "605",
                    "604",
                    "603",
                    "602",
                    "601",
                    "600",
                    "599"
                ],
                "past_outcome_list": [
                    "None",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "Failed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.algorithms.HB3AIntegratePeaksTest.HB3AIntegratePeaksTest",
                "build": "606",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "19.59",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.5.20221114.1209\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\nHB3AAdjustSampleNorm-[Notice] HB3AAdjustSampleNorm started\nLoadMD-[Notice] LoadMD started (child)\nLoadMD-[Notice] LoadMD successful, Duration 7.82 seconds\nSetGoniometer-[Notice] SetGoniometer started (child)\nSetGoniometer-[Notice] SetGoniometer successful, Duration 0.00 seconds\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE started (child)\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE successful, Duration 0.58 seconds\nDeleteWorkspace-[Notice] DeleteWorkspace started (child)\nDeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds\nLoadMD-[Notice] LoadMD started (child)\nLoadMD-[Notice] LoadMD successful, Duration 5.83 seconds\nSetGoniometer-[Notice] SetGoniometer started (child)\nSetGoniometer-[Notice] SetGoniometer successful, Duration 0.00 seconds\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE started (child)\nConvertHFIRSCDtoMDE-[Notice] ConvertHFIRSCDtoMDE successful, Duration 0.59 seconds\nDeleteWorkspace-[Notice] DeleteWorkspace started (child)\nDeleteWorkspace-[Notice] DeleteWorkspace successful, Duration 0.00 seconds\nMergeMD-[Notice] MergeMD started (child)\nMergeMD-[Notice] MergeMD successful, Duration 1.07 seconds\nDeleteWorkspaces-[Notice] DeleteWorkspaces started (child)\nDeleteWorkspaces-[Notice] DeleteWorkspaces successful, Duration 0.01 seconds\nHB3AAdjustSampleNorm-[Notice] HB3AAdjustSampleNorm successful, Duration 16.33 seconds\nHB3AFindPeaks-[Notice] HB3AFindPeaks started\nFindPeaksMD-[Notice] FindPeaksMD started (child)\nFindPeaksMD-[Notice] Number of peaks found: 26\nFindPeaksMD-[Notice] FindPeaksMD successful, Duration 0.00 seconds\nFindUBUsingFFT-[Notice] FindUBUsingFFT started (child)\nFindUBUsingFFT-[Notice] Error = 0.0173408\nFindUBUsingFFT-[Notice] UB = Matrix(3,3)0.0223361,0.0484886,-0.100805,-0.275231,0.0340218,0.00952149,0.0372822,0.267584,-0.00227044\nFindUBUsingFFT-[Notice] New UB will index 24 Peaks out of 26 with tolerance of  0.15\nFindUBUsingFFT-[Notice] Lattice Parameters:    3.645732    3.714062   10.206438   79.318951   79.944046   89.376487   133.686339\nFindUBUsingFFT-[Notice] Parameter Errors  :    0.009246    0.008566    0.021181    0.170299    0.181964    0.196921    0.546722\nFindUBUsingFFT-[Notice] FindUBUsingFFT successful, Duration 0.24 seconds\nShowPossibleCells-[Notice] ShowPossibleCells started (child)\nShowPossibleCells-[Notice] Num Cells : 6\nShowPossibleCells-[Notice] Form #15  Error: 0.0683  Tetragonal    I   Lat Par:   3.6457   3.7141  19.7478    90.086   89.646   89.376     267.37\nShowPossibleCells-[Notice] Form #16  Error: 0.1698  Orthorhombic  F   Lat Par:   5.2326   5.1760  19.7478    89.689   90.185   88.936     534.75\nShowPossibleCells-[Notice] Form #42  Error: 0.0284  Orthorhombic  I   Lat Par:   3.6457   3.7141  19.7478    89.914   90.354   89.376     267.37\nShowPossibleCells-[Notice] Form #10  Error: 0.0683  Monoclinic    C   Lat Par:   5.2326   5.1760  10.2064    89.427  104.668   91.064     267.37\nShowPossibleCells-[Notice] Form #37  Error: 0.0284  Monoclinic    I   Lat Par:   3.7141   3.6457  19.7478    89.646   89.914   90.624     267.37\nShowPossibleCells-[Notice] Form #31  Error: 0.0000  Triclinic     P   Lat Par:   3.6457   3.7141  10.2064    79.319   79.944   89.376     133.69\nShowPossibleCells-[Notice] ShowPossibleCells successful, Duration 0.01 seconds\nSelectCellOfType-[Notice] SelectCellOfType started (child)\nSelectCellOfType-[Notice] Form #16  Error: 0.1698  Orthorhombic  F   Lat Par:   5.2326   5.1760  19.7478    89.689   90.185   88.936     534.75\nSelectCellOfType-[Notice] Reduced to Conventional Cell Transformation Matrix =  -1 -1 0 1 -1 0 1 1 2 \nSelectCellOfType-[Notice] Re-indexed the peaks with the new UB. \nSelectCellOfType-[Notice] Now, 24 are indexed with average error 0.0194414\nSelectCellOfType-[Notice] SelectCellOfType successful, Duration 0.00 seconds\nOptimizeLatticeForCellType-[Notice] OptimizeLatticeForCellType started (child)\nOptimizeLatticeForCellType-[Notice] peaks  Lattice Parameters:    5.234869    5.257473   19.748138   90.000000   90.000000   90.000000   543.511918\nOptimizeLatticeForCellType-[Notice] Parameter Errors  :    0.004353    0.009826    0.013286    0.000000    0.000000    0.000000    1.170370\nIndexPeaks-[Notice] Run 183 indexed 10 peaks out of 11 with tolerance of 0.12\nIndexPeaks-[Notice]   Average error in h,k,l for indexed peaks =  0.0177215\nIndexPeaks-[Notice] Run 182 indexed 14 peaks out of 15 with tolerance of 0.12\nIndexPeaks-[Notice]   Average error in h,k,l for indexed peaks =  0.0192002\nIndexPeaks-[Notice] All runs indexed 24 peaks out of 26 with tolerance of 0.12\nIndexPeaks-[Notice]   Average error in h,k,l for indexed peaks =  0.018584\nIndexPeaks-[Notice] Lattice Parameters:    5.234869    5.257473   19.748138   90.000000   90.000000   90.000000   543.511918\nIndexPeaks-[Notice] Parameter Errors  :    0.004353    0.009826    0.013286    0.000000    0.000000    0.000000    1.170370\nOptimizeLatticeForCellType-[Notice] OptimizeLatticeForCellType successful, Duration 0.00 seconds\nHB3AFindPeaks-[Notice] HB3AFindPeaks successful, Duration 0.26 seconds\nIntegratePeaksMD-[Notice] IntegratePeaksMD started\nMaskBTP-[Error] Error in execution of algorithm MaskBTP:\nMaskBTP-[Error] Instrument &#x27;HB3A&#x27; not in the allowed list\nMaskBTP-[Error]   at line 94 in &#x27;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/Framework/PythonInterface/plugins/algorithms/MaskBTP.py&#x27;\nIntegratePeaksMD-[Error] Can&#x27;t execute MaskBTP algorithm for this instrument to set edge for IntegrateIfOnEdge option\nSegmentation fault\n\n          Start 2462: workbench.test_figureinteraction.test_figureinteraction\n"
            }
        }
    ]
}