{
    "data": [
        {
            "test_name": "PythonSANSQt5.beam_centre_presenter_test.beam_centre_presenter_test",
            "latest_failed_build": "2690",
            "agent_name": "Mac",
            "last_failed_outcome": "Flake",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "2695",
                    "2694",
                    "2693",
                    "2692",
                    "2691",
                    "2690",
                    "2689",
                    "2688",
                    "2687",
                    "2686",
                    "2685",
                    "2684",
                    "2683",
                    "2682",
                    "2681",
                    "2680",
                    "2679",
                    "2678",
                    "2677",
                    "2676",
                    "2675",
                    "2674",
                    "2673",
                    "2672",
                    "2671",
                    "2670",
                    "2669",
                    "2668",
                    "2667",
                    "2666"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Flake",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "PythonSANSQt5.beam_centre_presenter_test.beam_centre_presenter_test",
                "build": "2690",
                "agent_name": "Mac",
                "trial": 1,
                "outcome": "Failed",
                "test_time": "10.91",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230524.1549.dev32\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n.F.......SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.SANS-[Warning] Could not parse run number from filename, using the run number direct set in the file which is 12345\n.......\n======================================================================\nFAIL: test_copies_into_internal_model (beam_centre_presenter_test.BeamCentrePresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/scripts/test/SANS/gui_logic/beam_centre_presenter_test.py&quot;, line 150, in test_copies_into_internal_model\n    self.assertEqual(getattr(mocked_external_model, attr), getattr(self.presenter._beam_centre_model, attr))\nAssertionError: 0.0 != 3.85\n\n----------------------------------------------------------------------\nRan 17 tests in 3.676s\n\nFAILED (failures=1)\n\n          Start 2599: PythonSANSQt5.beam_centre_presenter_test.beam_centre_presenter_test\n"
            }
        },
        {
            "test_name": "python.EngineeringDiffraction.test_presenter.test_presenter",
            "latest_failed_build": "2687",
            "agent_name": "Mac",
            "last_failed_outcome": "Failed",
            "pipeline_name": "pull_requests-conda-osx",
            "problem_count": 1,
            "past_outcome": {
                "build_keys": [
                    "2695",
                    "2694",
                    "2693",
                    "2692",
                    "2691",
                    "2690",
                    "2689",
                    "2688",
                    "2687",
                    "2686",
                    "2685",
                    "2684",
                    "2683",
                    "2682",
                    "2681",
                    "2680",
                    "2679",
                    "2678",
                    "2677",
                    "2676",
                    "2675",
                    "2674",
                    "2673",
                    "2672",
                    "2671",
                    "2670",
                    "2669",
                    "2668",
                    "2667",
                    "2666"
                ],
                "past_outcome_list": [
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Passed",
                    "Failed",
                    "Passed",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None",
                    "None"
                ]
            },
            "last_stack_traces": {
                "test_name": "python.EngineeringDiffraction.test_presenter.test_presenter",
                "build": "2687",
                "agent_name": "Mac",
                "trial": 3,
                "outcome": "Failed",
                "test_time": "8.91",
                "stacktrace": "FrameworkManager-[Notice] Welcome to Mantid 6.6.20230524.1549.dev4\nFrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid\n..Python-[Notice] Starting to fit workspace ws1\nPython-[Notice] Starting to fit workspace ws2\nPython-[Notice] Serial fitting finished.\n..Python-[Notice] Starting to fit workspace ws1\nPython-[Notice] Starting to fit workspace ws2\nPython-[Notice] Sequential fitting finished.\n.......Python-[Warning] No plotted data to fit to\nFPython-[Warning] No plotted data to fit to\nF...\n======================================================================\nFAIL: test_fit_all_started_sequential (test_presenter.FittingPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py&quot;, line 169, in test_fit_all_started_sequential\n    self.presenter.disable_view.assert_called_once_with(fit_all=True)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 924, in assert_called_once_with\n    raise AssertionError(msg)\nAssertionError: Expected &#x27;mock&#x27; to be called once. Called 0 times.\n\n======================================================================\nFAIL: test_fit_all_started_serial (test_presenter.FittingPresenterTest)\n----------------------------------------------------------------------\nTraceback (most recent call last):\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/qt/python/mantidqtinterfaces/mantidqtinterfaces/Engineering/gui/engineering_diffraction/tabs/fitting/test/test_presenter.py&quot;, line 182, in test_fit_all_started_serial\n    self.presenter.disable_view.assert_called_once_with(fit_all=True)\n  File &quot;/Users/builder/Jenkins/workspace/pull_requests-conda-osx/mambaforge/envs/mantid-developer/lib/python3.8/unittest/mock.py&quot;, line 924, in assert_called_once_with\n    raise AssertionError(msg)\nAssertionError: Expected &#x27;mock&#x27; to be called once. Called 0 times.\n\n----------------------------------------------------------------------\nRan 16 tests in 1.156s\n\nFAILED (failures=2)\n\n          Start 1834: MDAlgorithmsTest_CalculateCoverageDGSTest\n"
            }
        }
    ]
}